# DEFAULT STATS:
from enum import Enum

DEFAULT_NAME = f"Bob"
DEFAULT_LEVEL = 1
DEFAULT_CHARACTER_CLASS = None
DEFAULT_HP = 100
DEFAULT_MP = 100
DEFAULT_ATT = 10
DEFAULT_DEF = 10
DEFAULT_SPD = 10

# RACE
class Race(Enum):
    HUMAN = 1
    ORC = 2
    NAZIR = 3
DEFAULT_RACE = Race(1)

# CLASS
class CharacterClass(Enum):
    WARRIOR = 1
    WARLOCK = 2
    SCOUNDREL = 3
DEFAULT_CHARACTER_CLASS = CharacterClass(1)