# busybox - super tiny image with shell:
FROM busybox

# Crete container in run echo in it:
RUN echo "building simple docker image"

# Command to start when the image is started:
CMD echo "hello container"

# D:\Projects\devop-learn\Docker>docker build -t hello .
